[Playstyle]
	#Defines the playstyle mode for the mod:
	#MODERN: Modern playstyle with new features and challenges.
	#ONE_TIER_ONLY [WIP]: Single-tier Mining Skill Card that upgrades to Mastered upon challenge completion.
	#LEGACY: Restores mechanics from v0.1.0 (only one miner certificate and one challenge).
	#Allowed Values: MODERN, ONE_TIER_ONLY, LEGACY
	playstyle_mode = "MODERN"
